/**
 * System Constants - DO NOT MODIFY UNLESS YOU UNDERSTAND THE IMPLICATIONS
 */
module.exports = {
  // Time
  MS_PER_SECOND: 1000,
  MS_PER_MINUTE: 60_000,
  MS_PER_HOUR: 3_600_000,
  MS_PER_DAY: 86_400_000,

  // KuCoin Futures
  KUCOIN_TAKER_FEE: 0.0006,
  KUCOIN_MAKER_FEE: 0.0002,
  KUCOIN_MAINT_MARGIN: 0.005,
  KUCOIN_MAX_LEVERAGE: 100,
  KUCOIN_MIN_LEVERAGE: 1,

  // Signal Thresholds
  SCORE_EXTREME_BUY: 90,
  SCORE_STRONG_BUY: 70,
  SCORE_BUY: 50,
  SCORE_WEAK_BUY: 30,
  SCORE_NEUTRAL: 0,
  SCORE_WEAK_SELL: -30,
  SCORE_SELL: -50,
  SCORE_STRONG_SELL: -70,
  SCORE_EXTREME_SELL: -90,

  // Risk Defaults
  DEFAULT_STOP_LOSS_ROI: 0.5,
  DEFAULT_TAKE_PROFIT_ROI: 2.0,
  DEFAULT_TRAILING_ACTIVATION: 1.0,
  DEFAULT_TRAILING_DISTANCE: 0.3,
  DEFAULT_TRAILING_STEP: 0.5,
  MIN_LIQUIDATION_BUFFER: 0.05,

  // System Limits
  MAX_OPEN_POSITIONS: 5,
  MAX_DAILY_DRAWDOWN: 5.0,
  MAX_CONSECUTIVE_LOSSES: 5,
  MAX_REQUESTS_PER_SECOND: 10,
  HEARTBEAT_TIMEOUT_MS: 30_000,
  MAX_ORDERBOOK_AGE_MS: 5_000,
  MIN_CANDLES_FOR_INDICATORS: 200
};
